# Generated by Django 6.0.4 on 2026-04-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="Deve alterar senha"),
        ),
    ]
