# Generated by Django 6.0.4 on 2026-04-10 22:09

import django.db.models.deletion
import medicos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, unique=True, verbose_name="Nome"),
                ),
            ],
            options={
                "verbose_name": "Especialidade",
                "verbose_name_plural": "Especialidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=250, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de nascimento"),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=medicos.models.upload_foto,
                        verbose_name="Foto de perfil",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(max_length=250, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "instituicao_formacao",
                    models.CharField(
                        max_length=250, verbose_name="Instituição de formação"
                    ),
                ),
                (
                    "ano_formatura",
                    models.PositiveSmallIntegerField(verbose_name="Ano de formatura"),
                ),
                (
                    "link_lattes",
                    models.URLField(blank=True, verbose_name="Currículo Lattes"),
                ),
                (
                    "crm_numero",
                    models.CharField(max_length=20, verbose_name="Número do CRM"),
                ),
                (
                    "crm_estado",
                    models.CharField(
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="Estado do CRM",
                    ),
                ),
                (
                    "tipo_chave_pix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cpf", "CPF"),
                            ("cnpj", "CNPJ"),
                            ("email", "E-mail"),
                            ("telefone", "Telefone"),
                            ("aleatoria", "Chave Aleatória"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de chave PIX",
                    ),
                ),
                (
                    "chave_pix",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Chave PIX"
                    ),
                ),
                (
                    "diploma_medico",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=medicos.models.upload_diploma,
                        verbose_name="Diploma médico",
                    ),
                ),
                (
                    "declaracao_quitacao_crm",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=medicos.models.upload_quitacao,
                        verbose_name="Declaração de quitação com CRM",
                    ),
                ),
                (
                    "etica_crm",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=medicos.models.upload_etica,
                        verbose_name="Declaração de ética com CRM",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medico",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médico",
                "verbose_name_plural": "Médicos",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="MedicoEspecialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=medicos.models.upload_comprovante,
                        verbose_name="Comprovante de especialidade",
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "especialidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medicos.especialidade",
                        verbose_name="Especialidade",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprovantes_especialidade",
                        to="medicos.medico",
                        verbose_name="Médico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante de Especialidade",
                "verbose_name_plural": "Comprovantes de Especialidade",
                "unique_together": {("medico", "especialidade")},
            },
        ),
        migrations.AddField(
            model_name="medico",
            name="especialidades",
            field=models.ManyToManyField(
                blank=True,
                through="medicos.MedicoEspecialidade",
                to="medicos.especialidade",
                verbose_name="Especialidades",
            ),
        ),
    ]
