# Generated by Django 6.0.4 on 2026-04-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="ano_formatura",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Ano de formatura"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="medico",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="medico",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="medico",
            name="crm_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                verbose_name="Estado do CRM",
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="crm_numero",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Número do CRM"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="medico",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="instituicao_formacao",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Instituição de formação"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="logradouro",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="numero",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="medico",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
    ]
