# Generated by Django 6.0.4 on 2026-04-11 00:41

import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0002_alter_medico_ano_formatura_alter_medico_bairro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medico",
            name="comprovante_endereco",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=medicos.models.upload_comprovante_endereco,
                verbose_name="Comprovante de endereço",
            ),
        ),
        migrations.AddField(
            model_name="medico",
            name="rg",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=medicos.models.upload_rg,
                verbose_name="RG",
            ),
        ),
    ]
