# Generated by Django 6.0.4 on 2026-04-11 01:58

import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0007_merge_rg_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="declaracao_quitacao_crm",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=medicos.models.upload_quitacao,
                verbose_name="Certidão de regularidade fiscal CRM",
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="etica_crm",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=medicos.models.upload_etica,
                verbose_name="Certidão Ético-profissional CRM",
            ),
        ),
    ]
