# Generated by Django 6.0.4 on 2026-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="Corpo Clínico", max_length=100)),
                (
                    "subtitulo",
                    models.CharField(
                        default="Gestão de Profissionais de Saúde", max_length=200
                    ),
                ),
                ("cor_primaria", models.CharField(default="#1d4ed8", max_length=7)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="config/logo/"),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
    ]
